# Stage 1 - Builder
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY app/package*.json ./

RUN npm install

COPY app/ .

# Stage 2 - Production
FROM node:18-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

EXPOSE 3000

CMD ["node", "app.js"]